### ISSUE TITLE
Unable to create oauth token

### ISSUE THREAD

**Issue by Paktosan** [kif-ev/oskiosk-server#141]
Hi,
I am having issues creating a oauth token. Can you help me out with that? Here is the output I got when trying to create one:
```
[kiosk@oskiosk oskiosk-server]$ rake oauth:create_app[kiosk\(,admin\)] --trace
** Invoke oauth:create_app (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute oauth:create_app
rake aborted!
NameError: uninitialized constant Doorkeeper::Application
/home/kiosk/oskiosk-server/lib/tasks/oauth.rake:14:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.4.6/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/usr/local/rvm/gems/ruby-2.4.6/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/usr/local/rvm/gems/ruby-2.4.6/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/usr/local/rvm/gems/ruby-2.4.6/gems/bugsnag-6.11.1/lib/bugsnag/integrations/rake.rb:18:in `execute_with_bugsnag'
/usr/local/rvm/gems/ruby-2.4.6/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.4.6/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/usr/local/rvm/gems/ruby-2.4.6/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/usr/local/rvm/gems/ruby-2.4.6/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
/usr/local/rvm/gems/ruby-2.4.6/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
/usr/local/rvm/gems/ruby-2.4.6/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/local/rvm/gems/ruby-2.4.6/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
/usr/local/rvm/gems/ruby-2.4.6/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
/usr/local/rvm/gems/ruby-2.4.6/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
/usr/local/rvm/gems/ruby-2.4.6/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
/usr/local/rvm/gems/ruby-2.4.6/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
/usr/local/rvm/gems/ruby-2.4.6/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.4.6/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
/usr/local/rvm/gems/ruby-2.4.6/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.6/bin/rake:23:in `load'
/usr/local/rvm/gems/ruby-2.4.6/bin/rake:23:in `<main>'
/usr/local/rvm/gems/ruby-2.4.6/bin/ruby_executable_hooks:24:in `eval'
/usr/local/rvm/gems/ruby-2.4.6/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => oauth:create_app
```

**Comment by thegcat** [comment]
Thank you for the report. Unfortunately I haven't been able to find out why this error happens. I have opened an issue with Doorkeeper https://github.com/doorkeeper-gem/doorkeeper/issues/1281

Please also note that the correct rake invocation would be `rake oauth:create_app[kiosk,admin]`, the `( )` in the README only denote the optional nature of the `TYPE` parameter.

**Comment by Paktosan** [comment]
I was able to work around the issue by running the tasks code manually in the rails console for now.

**Comment by thegcat** [comment]
We haven't found the issue but there's a workaround in the rake task now.

**Comment by Paktosan** [comment]
Thanks, will try the fix soon!
